// <auto-generated />
using System;
using LitigApp.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LitigApp.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260604140948_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LitigApp.Domain.Catalog.City", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(5)")
                        .HasColumnName("id")
                        .IsFixedLength();

                    b.Property<string>("DepartmentId")
                        .IsRequired()
                        .HasColumnType("char(2)")
                        .HasColumnName("department_id")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_cities");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("idx_cities_dept");

                    b.ToTable("cities", (string)null);
                });

            modelBuilder.Entity("LitigApp.Domain.Catalog.Court", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CityId")
                        .IsRequired()
                        .HasColumnType("char(5)")
                        .HasColumnName("city_id")
                        .IsFixedLength();

                    b.Property<short?>("CourtNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("court_number");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("EntityCode")
                        .HasColumnType("char(2)")
                        .HasColumnName("entity_code")
                        .IsFixedLength();

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_synced_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("OfficialCode")
                        .IsRequired()
                        .HasColumnType("char(12)")
                        .HasColumnName("official_code")
                        .IsFixedLength();

                    b.Property<string>("RawPayload")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_payload");

                    b.Property<string>("SpecialtyCode")
                        .HasColumnType("char(2)")
                        .HasColumnName("specialty_code")
                        .IsFixedLength();

                    b.HasKey("Id")
                        .HasName("pk_courts");

                    b.HasIndex("EntityCode")
                        .HasDatabaseName("ix_courts_entity_code");

                    b.HasIndex("Name")
                        .HasDatabaseName("idx_courts_name_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Name"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Name"), new[] { "gin_trgm_ops" });

                    b.HasIndex("OfficialCode")
                        .IsUnique()
                        .HasDatabaseName("ix_courts_official_code");

                    b.HasIndex("SpecialtyCode")
                        .HasDatabaseName("ix_courts_specialty_code");

                    b.HasIndex("CityId", "SpecialtyCode")
                        .HasDatabaseName("idx_courts_city_spec");

                    b.ToTable("courts", (string)null);
                });

            modelBuilder.Entity("LitigApp.Domain.Catalog.Department", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(2)")
                        .HasColumnName("id")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_departments");

                    b.ToTable("departments", (string)null);
                });

            modelBuilder.Entity("LitigApp.Domain.Catalog.Entity", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("char(2)")
                        .HasColumnName("code")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Code")
                        .HasName("pk_entities");

                    b.ToTable("entities", (string)null);
                });

            modelBuilder.Entity("LitigApp.Domain.Catalog.Specialty", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("char(2)")
                        .HasColumnName("code")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Code")
                        .HasName("pk_specialties");

                    b.ToTable("specialties", (string)null);
                });

            modelBuilder.Entity("LitigApp.Domain.Common.SyncState", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<string>("ValueText")
                        .HasColumnType("text")
                        .HasColumnName("value_text");

                    b.Property<DateTimeOffset?>("ValueTimestamp")
                        .HasColumnType("timestamptz")
                        .HasColumnName("value_timestamp");

                    b.HasKey("Key")
                        .HasName("pk_sync_state");

                    b.ToTable("sync_state", (string)null);
                });

            modelBuilder.Entity("LitigApp.Domain.Imports.ImportJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ColumnMapping")
                        .HasColumnType("jsonb")
                        .HasColumnName("column_mapping");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<int>("ErrorCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("error_count");

                    b.Property<string>("Errors")
                        .HasColumnType("jsonb")
                        .HasColumnName("errors");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<int>("ProcessedRows")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("processed_rows");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.Property<int>("SuccessCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("success_count");

                    b.Property<int>("TotalRows")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_rows");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_import_jobs");

                    b.HasIndex("UserId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_imports_user_created");

                    b.ToTable("import_jobs", (string)null);
                });

            modelBuilder.Entity("LitigApp.Domain.Notifications.NotificationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<Guid?>("OutboxId")
                        .HasColumnType("uuid")
                        .HasColumnName("outbox_id");

                    b.PrimitiveCollection<Guid[]>("ProcessIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("process_ids");

                    b.Property<string>("ProviderMessageId")
                        .HasColumnType("text")
                        .HasColumnName("provider_message_id");

                    b.Property<string>("RawResponse")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_response");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notification_logs");

                    b.HasIndex("OutboxId")
                        .HasDatabaseName("ix_notification_logs_outbox_id");

                    b.HasIndex("UserId", "SentAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_notif_logs_user_sent");

                    b.ToTable("notification_logs", (string)null);
                });

            modelBuilder.Entity("LitigApp.Domain.Notifications.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("attempts");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("processed_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notifications_outbox");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("idx_outbox_status_created")
                        .HasFilter("status IN ('pending', 'processing')");

                    b.ToTable("notifications_outbox", (string)null);
                });

            modelBuilder.Entity("LitigApp.Domain.Processes.Process", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Attended")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("attended");

                    b.Property<Guid?>("CourtId")
                        .HasColumnType("uuid")
                        .HasColumnName("court_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentStatus")
                        .HasColumnType("text")
                        .HasColumnName("current_status");

                    b.Property<string>("CustomAlias")
                        .HasColumnType("text")
                        .HasColumnName("custom_alias");

                    b.Property<int?>("ExternalConnectionId")
                        .HasColumnType("integer")
                        .HasColumnName("external_connection_id");

                    b.Property<long?>("ExternalProcessId")
                        .HasColumnType("bigint")
                        .HasColumnName("external_process_id");

                    b.Property<string>("FileNumber")
                        .IsRequired()
                        .HasColumnType("char(23)")
                        .HasColumnName("file_number");

                    b.Property<string>("FilingContent")
                        .HasColumnType("text")
                        .HasColumnName("filing_content");

                    b.Property<short?>("FilingYear")
                        .HasColumnType("smallint")
                        .HasColumnName("filing_year");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsPrivate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_private");

                    b.Property<string>("JudgeName")
                        .HasColumnType("text")
                        .HasColumnName("judge_name");

                    b.Property<DateTimeOffset?>("LastCourtActionAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_court_action_at");

                    b.Property<int>("LastExternalConsecutive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("last_external_consecutive");

                    b.Property<DateTimeOffset?>("LastSyncAttemptAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_sync_attempt_at");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_synced_at");

                    b.Property<string>("ProcessClass")
                        .HasColumnType("text")
                        .HasColumnName("process_class");

                    b.Property<string>("ProcessSubclass")
                        .HasColumnType("text")
                        .HasColumnName("process_subclass");

                    b.Property<string>("ProcessType")
                        .HasColumnType("text")
                        .HasColumnName("process_type");

                    b.Property<string>("Resource")
                        .HasColumnType("text")
                        .HasColumnName("resource");

                    b.Property<int>("SyncAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sync_attempts");

                    b.Property<string>("SyncError")
                        .HasColumnType("text")
                        .HasColumnName("sync_error");

                    b.Property<string>("SyncPhase")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("pending_initial_full")
                        .HasColumnName("sync_phase");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("pending")
                        .HasColumnName("sync_status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_processes");

                    b.HasIndex("CourtId")
                        .HasDatabaseName("ix_processes_court_id");

                    b.HasIndex("ExternalProcessId")
                        .HasDatabaseName("idx_processes_external");

                    b.HasIndex("SyncPhase", "LastSyncAttemptAt")
                        .HasDatabaseName("idx_processes_sync_phase")
                        .HasFilter("is_active = true");

                    b.HasIndex("UserId", "FileNumber")
                        .IsUnique()
                        .HasDatabaseName("uq_processes_user_file");

                    b.HasIndex("UserId", "Attended", "LastCourtActionAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("idx_processes_user_attended");

                    b.HasIndex("UserId", "IsActive", "LastCourtActionAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("idx_processes_user_active");

                    b.ToTable("processes", null, t =>
                        {
                            t.HasCheckConstraint("chk_processes_file_length", "length(file_number) = 23");
                        });
                });

            modelBuilder.Entity("LitigApp.Domain.Processes.ProcessAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<DateOnly?>("ActionDate")
                        .HasColumnType("date")
                        .HasColumnName("action_date");

                    b.Property<string>("Annotation")
                        .HasColumnType("text")
                        .HasColumnName("annotation");

                    b.Property<int>("ConsecutiveNumber")
                        .HasColumnType("integer")
                        .HasColumnName("consecutive_number");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<long>("ExternalActionId")
                        .HasColumnType("bigint")
                        .HasColumnName("external_action_id");

                    b.Property<Guid?>("GroupedWithId")
                        .HasColumnType("uuid")
                        .HasColumnName("grouped_with_id");

                    b.Property<bool>("HasDocuments")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("has_documents");

                    b.Property<Guid>("ProcessId")
                        .HasColumnType("uuid")
                        .HasColumnName("process_id");

                    b.Property<string>("RawPayload")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_payload");

                    b.Property<DateOnly?>("RecordedAt")
                        .HasColumnType("date")
                        .HasColumnName("recorded_at");

                    b.Property<string>("RuleCode")
                        .HasColumnType("text")
                        .HasColumnName("rule_code");

                    b.Property<DateOnly?>("TermEndDate")
                        .HasColumnType("date")
                        .HasColumnName("term_end_date");

                    b.Property<DateOnly?>("TermStartDate")
                        .HasColumnType("date")
                        .HasColumnName("term_start_date");

                    b.HasKey("Id")
                        .HasName("pk_process_actions");

                    b.HasIndex("GroupedWithId")
                        .HasDatabaseName("ix_process_actions_grouped_with_id");

                    b.HasIndex("ProcessId", "ConsecutiveNumber")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_actions_process_consec");

                    b.HasIndex("ProcessId", "ExternalActionId")
                        .IsUnique()
                        .HasDatabaseName("uq_actions_process_external");

                    b.HasIndex("ProcessId", "RecordedAt")
                        .HasDatabaseName("idx_actions_process_recorded");

                    b.ToTable("process_actions", (string)null);
                });

            modelBuilder.Entity("LitigApp.Domain.Processes.ProcessSubject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<long?>("ExternalSubjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("external_subject_id");

                    b.Property<string>("Identification")
                        .HasColumnType("text")
                        .HasColumnName("identification");

                    b.Property<bool>("IsSummoned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_summoned");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("ProcessId")
                        .HasColumnType("uuid")
                        .HasColumnName("process_id");

                    b.Property<string>("RawPayload")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_payload");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("api")
                        .HasColumnName("source");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject_type");

                    b.HasKey("Id")
                        .HasName("pk_process_subjects");

                    b.HasIndex("ProcessId", "SubjectType")
                        .HasDatabaseName("idx_subjects_process_type");

                    b.ToTable("process_subjects", (string)null);
                });

            modelBuilder.Entity("LitigApp.Domain.Users.UserNotificationPreferences", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<bool>("EmailEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("email_enabled");

                    b.Property<TimeOnly?>("QuietHoursEnd")
                        .HasColumnType("time")
                        .HasColumnName("quiet_hours_end");

                    b.Property<TimeOnly?>("QuietHoursStart")
                        .HasColumnType("time")
                        .HasColumnName("quiet_hours_start");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<bool>("WhatsAppEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("whats_app_enabled");

                    b.HasKey("UserId")
                        .HasName("pk_user_notification_preferences");

                    b.ToTable("user_notification_preferences", (string)null);
                });

            modelBuilder.Entity("LitigApp.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.Property<string>("WhatsAppPhone")
                        .HasColumnType("text")
                        .HasColumnName("whats_app_phone");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_role_claims_role_id");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_claims_user_id");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_logins_user_id");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("RoleId")
                        .HasColumnType("text")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_asp_net_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_user_roles_role_id");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_asp_net_user_tokens");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("LitigApp.Domain.Catalog.City", b =>
                {
                    b.HasOne("LitigApp.Domain.Catalog.Department", "Department")
                        .WithMany("Cities")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cities_departments_department_id");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("LitigApp.Domain.Catalog.Court", b =>
                {
                    b.HasOne("LitigApp.Domain.Catalog.City", "City")
                        .WithMany("Courts")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_courts_cities_city_id");

                    b.HasOne("LitigApp.Domain.Catalog.Entity", "JudicialEntity")
                        .WithMany("Courts")
                        .HasForeignKey("EntityCode")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_courts_entities_entity_code");

                    b.HasOne("LitigApp.Domain.Catalog.Specialty", "Specialty")
                        .WithMany("Courts")
                        .HasForeignKey("SpecialtyCode")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_courts_specialties_specialty_code");

                    b.Navigation("City");

                    b.Navigation("JudicialEntity");

                    b.Navigation("Specialty");
                });

            modelBuilder.Entity("LitigApp.Domain.Notifications.NotificationLog", b =>
                {
                    b.HasOne("LitigApp.Domain.Notifications.OutboxMessage", "Outbox")
                        .WithMany()
                        .HasForeignKey("OutboxId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_notification_logs_outbox_messages_outbox_id");

                    b.Navigation("Outbox");
                });

            modelBuilder.Entity("LitigApp.Domain.Processes.Process", b =>
                {
                    b.HasOne("LitigApp.Domain.Catalog.Court", "Court")
                        .WithMany()
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_processes_courts_court_id");

                    b.Navigation("Court");
                });

            modelBuilder.Entity("LitigApp.Domain.Processes.ProcessAction", b =>
                {
                    b.HasOne("LitigApp.Domain.Processes.ProcessAction", "GroupedWith")
                        .WithMany()
                        .HasForeignKey("GroupedWithId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_process_actions_process_actions_grouped_with_id");

                    b.HasOne("LitigApp.Domain.Processes.Process", "Process")
                        .WithMany("Actions")
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_process_actions_processes_process_id");

                    b.Navigation("GroupedWith");

                    b.Navigation("Process");
                });

            modelBuilder.Entity("LitigApp.Domain.Processes.ProcessSubject", b =>
                {
                    b.HasOne("LitigApp.Domain.Processes.Process", "Process")
                        .WithMany("Subjects")
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_process_subjects_processes_process_id");

                    b.Navigation("Process");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_role_claims_asp_net_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("LitigApp.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("LitigApp.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_roles_role_id");

                    b.HasOne("LitigApp.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("LitigApp.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_tokens_asp_net_users_user_id");
                });

            modelBuilder.Entity("LitigApp.Domain.Catalog.City", b =>
                {
                    b.Navigation("Courts");
                });

            modelBuilder.Entity("LitigApp.Domain.Catalog.Department", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("LitigApp.Domain.Catalog.Entity", b =>
                {
                    b.Navigation("Courts");
                });

            modelBuilder.Entity("LitigApp.Domain.Catalog.Specialty", b =>
                {
                    b.Navigation("Courts");
                });

            modelBuilder.Entity("LitigApp.Domain.Processes.Process", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("Subjects");
                });
#pragma warning restore 612, 618
        }
    }
}
