// <auto-generated />
using System;
using LitigApp.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LitigApp.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LitigApp.Domain.Catalog.City", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<short>("DepartmentId")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("idx_cities_dept");

                    b.ToTable("cities", (string)null);
                });

            modelBuilder.Entity("LitigApp.Domain.Catalog.Court", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CityId")
                        .HasColumnType("integer");

                    b.Property<short?>("CourtNumber")
                        .HasColumnType("smallint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<short?>("EntityId")
                        .HasColumnType("smallint");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OfficialCode")
                        .IsRequired()
                        .HasColumnType("char(12)");

                    b.Property<string>("RawPayload")
                        .HasColumnType("jsonb");

                    b.Property<short?>("SpecialtyId")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.HasIndex("Name")
                        .HasDatabaseName("idx_courts_name_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Name"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Name"), new[] { "gin_trgm_ops" });

                    b.HasIndex("OfficialCode")
                        .IsUnique()
                        .HasDatabaseName("ix_courts_official_code");

                    b.HasIndex("SpecialtyId");

                    b.HasIndex("CityId", "SpecialtyId")
                        .HasDatabaseName("idx_courts_city_spec");

                    b.ToTable("courts", (string)null);
                });

            modelBuilder.Entity("LitigApp.Domain.Catalog.Department", b =>
                {
                    b.Property<short>("Id")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("departments", (string)null);
                });

            modelBuilder.Entity("LitigApp.Domain.Catalog.Entity", b =>
                {
                    b.Property<short>("Id")
                        .HasColumnType("smallint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("char(2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_entities_code");

                    b.ToTable("entities", (string)null);
                });

            modelBuilder.Entity("LitigApp.Domain.Catalog.Specialty", b =>
                {
                    b.Property<short>("Id")
                        .HasColumnType("smallint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("char(2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_specialties_code");

                    b.ToTable("specialties", (string)null);
                });

            modelBuilder.Entity("LitigApp.Domain.Common.SyncState", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("ValueText")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ValueTimestamp")
                        .HasColumnType("timestamptz");

                    b.HasKey("Key");

                    b.ToTable("sync_state", (string)null);
                });

            modelBuilder.Entity("LitigApp.Domain.Imports.ImportJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ColumnMapping")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<int>("ErrorCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Errors")
                        .HasColumnType("jsonb");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProcessedRows")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("pending");

                    b.Property<int>("SuccessCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("TotalRows")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_imports_user_created");

                    b.ToTable("import_jobs", (string)null);
                });

            modelBuilder.Entity("LitigApp.Domain.Notifications.NotificationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("OutboxId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<Guid[]>("ProcessIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<string>("ProviderMessageId")
                        .HasColumnType("text");

                    b.Property<string>("RawResponse")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OutboxId");

                    b.HasIndex("UserId", "SentAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_notif_logs_user_sent");

                    b.ToTable("notification_logs", (string)null);
                });

            modelBuilder.Entity("LitigApp.Domain.Notifications.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<short>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0);

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("pending");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("idx_outbox_status_created")
                        .HasFilter("status IN ('pending', 'processing')");

                    b.ToTable("notifications_outbox", (string)null);
                });

            modelBuilder.Entity("LitigApp.Domain.Processes.Process", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Attended")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid?>("CourtId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("CurrentStatus")
                        .HasColumnType("text");

                    b.Property<string>("CustomAlias")
                        .HasColumnType("text");

                    b.Property<int?>("ExternalConnectionId")
                        .HasColumnType("integer");

                    b.Property<long?>("ExternalProcessId")
                        .HasColumnType("bigint");

                    b.Property<string>("FileNumber")
                        .IsRequired()
                        .HasColumnType("char(23)");

                    b.Property<string>("FilingContent")
                        .HasColumnType("text");

                    b.Property<short?>("FilingYear")
                        .HasColumnType("smallint");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsPrivate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("JudgeName")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastCourtActionAt")
                        .HasColumnType("timestamptz");

                    b.Property<int>("LastExternalConsecutive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset?>("LastSyncAttemptAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("ProcessClass")
                        .HasColumnType("text");

                    b.Property<string>("ProcessSubclass")
                        .HasColumnType("text");

                    b.Property<string>("ProcessType")
                        .HasColumnType("text");

                    b.Property<string>("Resource")
                        .HasColumnType("text");

                    b.Property<int>("SyncAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("SyncError")
                        .HasColumnType("text");

                    b.Property<string>("SyncPhase")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("pending_initial_full");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("pending");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CourtId");

                    b.HasIndex("ExternalProcessId")
                        .HasDatabaseName("idx_processes_external");

                    b.HasIndex("SyncPhase", "LastSyncAttemptAt")
                        .HasDatabaseName("idx_processes_sync_phase")
                        .HasFilter("is_active = true");

                    b.HasIndex("UserId", "FileNumber")
                        .IsUnique()
                        .HasDatabaseName("uq_processes_user_file");

                    b.HasIndex("UserId", "Attended", "LastCourtActionAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("idx_processes_user_attended");

                    b.HasIndex("UserId", "IsActive", "LastCourtActionAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("idx_processes_user_active");

                    b.ToTable("processes", null, t =>
                        {
                            t.HasCheckConstraint("chk_processes_file_length", "length(file_number) = 23");
                        });
                });

            modelBuilder.Entity("LitigApp.Domain.Processes.ProcessAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("ActionDate")
                        .HasColumnType("date");

                    b.Property<string>("Annotation")
                        .HasColumnType("text");

                    b.Property<int>("ConsecutiveNumber")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<long>("ExternalActionId")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("GroupedWithId")
                        .HasColumnType("uuid");

                    b.Property<bool>("HasDocuments")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("ProcessId")
                        .HasColumnType("uuid");

                    b.Property<string>("RawPayload")
                        .HasColumnType("jsonb");

                    b.Property<DateOnly?>("RecordedAt")
                        .HasColumnType("date");

                    b.Property<string>("RuleCode")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("TermEndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("TermStartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("GroupedWithId");

                    b.HasIndex("ProcessId", "ConsecutiveNumber")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_actions_process_consec");

                    b.HasIndex("ProcessId", "ExternalActionId")
                        .IsUnique()
                        .HasDatabaseName("uq_actions_process_external");

                    b.HasIndex("ProcessId", "RecordedAt")
                        .HasDatabaseName("idx_actions_process_recorded");

                    b.ToTable("process_actions", (string)null);
                });

            modelBuilder.Entity("LitigApp.Domain.Processes.ProcessSubject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<long?>("ExternalSubjectId")
                        .HasColumnType("bigint");

                    b.Property<string>("Identification")
                        .HasColumnType("text");

                    b.Property<bool>("IsSummoned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProcessId")
                        .HasColumnType("uuid");

                    b.Property<string>("RawPayload")
                        .HasColumnType("jsonb");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("api");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProcessId", "SubjectType")
                        .HasDatabaseName("idx_subjects_process_type");

                    b.ToTable("process_subjects", (string)null);
                });

            modelBuilder.Entity("LitigApp.Domain.Users.UserNotificationPreferences", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<bool>("EmailEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<TimeOnly?>("QuietHoursEnd")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("QuietHoursStart")
                        .HasColumnType("time");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<bool>("WhatsAppEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.HasKey("UserId");

                    b.ToTable("user_notification_preferences", (string)null);
                });

            modelBuilder.Entity("LitigApp.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("WhatsAppPhone")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("LitigApp.Domain.Catalog.City", b =>
                {
                    b.HasOne("LitigApp.Domain.Catalog.Department", "Department")
                        .WithMany("Cities")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("LitigApp.Domain.Catalog.Court", b =>
                {
                    b.HasOne("LitigApp.Domain.Catalog.City", "City")
                        .WithMany("Courts")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LitigApp.Domain.Catalog.Entity", "JudicialEntity")
                        .WithMany("Courts")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LitigApp.Domain.Catalog.Specialty", "Specialty")
                        .WithMany("Courts")
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("City");

                    b.Navigation("JudicialEntity");

                    b.Navigation("Specialty");
                });

            modelBuilder.Entity("LitigApp.Domain.Notifications.NotificationLog", b =>
                {
                    b.HasOne("LitigApp.Domain.Notifications.OutboxMessage", "Outbox")
                        .WithMany()
                        .HasForeignKey("OutboxId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Outbox");
                });

            modelBuilder.Entity("LitigApp.Domain.Processes.Process", b =>
                {
                    b.HasOne("LitigApp.Domain.Catalog.Court", "Court")
                        .WithMany()
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Court");
                });

            modelBuilder.Entity("LitigApp.Domain.Processes.ProcessAction", b =>
                {
                    b.HasOne("LitigApp.Domain.Processes.ProcessAction", "GroupedWith")
                        .WithMany()
                        .HasForeignKey("GroupedWithId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LitigApp.Domain.Processes.Process", "Process")
                        .WithMany("Actions")
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroupedWith");

                    b.Navigation("Process");
                });

            modelBuilder.Entity("LitigApp.Domain.Processes.ProcessSubject", b =>
                {
                    b.HasOne("LitigApp.Domain.Processes.Process", "Process")
                        .WithMany("Subjects")
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Process");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("LitigApp.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("LitigApp.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LitigApp.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("LitigApp.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LitigApp.Domain.Catalog.City", b =>
                {
                    b.Navigation("Courts");
                });

            modelBuilder.Entity("LitigApp.Domain.Catalog.Department", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("LitigApp.Domain.Catalog.Entity", b =>
                {
                    b.Navigation("Courts");
                });

            modelBuilder.Entity("LitigApp.Domain.Catalog.Specialty", b =>
                {
                    b.Navigation("Courts");
                });

            modelBuilder.Entity("LitigApp.Domain.Processes.Process", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("Subjects");
                });
#pragma warning restore 612, 618
        }
    }
}
